import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Sidebar } from "@/components/sidebar/page";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    <div className="flex flex-col md:flex-row ">
      <div className="flex w-full md:w-[25%] xl:w-[15%] ">
        <Sidebar />
      </div>
      <div className="flex w-full xl:w-[85%] ">
        {children}
        </div>
    </div>
      </body>
    </html>
  );
}
